### PR TITLE
Update to latest OCTGN script API

### PR DESCRIPTION
**Pull request by ibbo**
This should fix the issues with the latest version of OCTGN.

I rushed it as I had limited time, so it's not well tested and I didn't have chance to clean it up much. It includes a new feature I worked on to make the saving and loading of table state use system dialogs. I hope it can help you get the LOTR plugin fixed more quickly.

### CODE REVIEW

**Comment by wlk0** [comment]
For easier maintenance, I'd remove the try/except handler and the legacy askString code now saveFileDlg/OpenFileDlg are officially available.

**Comment by wlk0** [comment]
Btw, the "filename" parameter in saveFileDlg/openFileDlg is never used in Octgn.
Not a major issue but the default path is now changed for previous saved game.

**Comment by ibbo** [comment]
> For easier maintenance, I'd remove the try/except handler and the legacy askString code now saveFileDlg/OpenFileDlg are officially available.

As you pointed out on Discord, it's quite difficult to prevent OCTGN from updating, so there's not much point including the legacy askString. I'll remove it.

> Btw, the "filename" parameter in saveFileDlg/openFileDlg is never used in Octgn.
> Not a major issue but the default path is now changed for previous saved game.

I'm not sure what you mean by that. The parameter was supposed to set the default path that the dialog opened with. You can see in my original pull request that it's passed all the way through to the system dialog: https://github.com/octgn/OCTGN/pull/2007/files

What makes you say it wasn't used in OCTGN? It's possible that I'm not setting that parameter correctly from this script.

**Comment by wlk0** [comment]
In this part of the code, the default value is never used, so the parameter has no effect atm:
image

**Comment by ibbo** [comment]
Oh yes, good spot. Not sure how I missed that. I'm currently documenting the new API functions for OCTGN, so a parameter that's not used is not great! I'll look at submitting a fix for this to OCTGN.

**Comment by ibbo** [comment]
Ok I've updated this to remove the fallback code. I've played through a couple of quests and saved/loaded the table state a few times now without any errors. I think this is probably good to go unless you have any more concerns. There's definitely a possibility I've missed something, as there's a lot of code to cover, and I don't know how best to try and do an exhaustive test.

**Comment by wlk0** [comment]
Good to go, nice job.
Now it's in Seastan's hands.

**Comment by ibbo** [comment]
I've continued to test this patch, and I've found another issue with it. With 2-players when I start a new round the 2nd player is triggering the resource phase twice i.e. all their heroes gain 2 resources and they draw 2 cards.

I'll look into it and try and fix it.

This makes me wonder if there's any way to get more testing on this patch before rolling it out to everyone? I'll happily plod away at the testing, but I'm sure I won't manage to catch everything.

**Comment by ibbo** [comment]
I've found and fixed that bug. In the new python API OCTGN fixed a bug that meant that not all players got the OnPlayerGlobalVariableChanged event. There was code in place to workaround this bug, which was now causing things to trigger twice. I've removed that workaround code and everything looks good again.

**Comment by ibbo** [comment]
@seastan - just noticed that you merged this and then reverted it. I guess there were still some problems with it? I'm happy to try and fix any issues you found. Can you let me know what the problems were?

**Comment by seastan** [comment]
@ibbo I'm not sure if it was the only issue, but there we a few functions that moved from multi-argument to a single dictionary argument that were broken in the update, and I haven't had time to figure out all the affected functions and what they now expect.

**Pull request merged**
